/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aMnnrqKwrFo
 */
import { Button } from '@/components/ui/button';
import { buttonVariants } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import Link from 'next/link';

export function Features() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 pb-24">
      <h2 className="text-2xl md:text-3xl font-bold tracking-tighter sm:text-4xl xl:text-5xl/none text-black text-center mb-8">
        Resources
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="shadow-lg p-6 rounded-lg">
          <div className="flex items-center justify-center text-5xl font-bold mb-4">
            300+
          </div>
          <h3 className="text-lg font-semibold mb-2">Explore Companies</h3>
          <p className="text-gray-600 mb-4">
            Directory of companies and open source projects building tools to
            query, analyze, and visualize blockchain data.
          </p>
          <Link
            className={buttonVariants({ variant: 'default' })}
            href="/blockchain-data"
          >
            View
          </Link>{' '}
        </Card>
        {/* <Card className="shadow-lg p-6 rounded-lg">
          <div className="flex items-center justify-center text-5xl font-bold mb-4">
            {'< 1 sec'}
          </div>
          <h3 className="text-lg font-semibold mb-2">Ethereum Latency</h3>
          <p className="text-gray-600 mb-4">
            See how fast blockchain data providers can retrieve data from the
            Ethereum blockchain.
          </p>
          <Link
            className={buttonVariants({ variant: 'default' })}
            href="/eth-performance"
          >
            Speed Test
          </Link>{' '}
        </Card> */}
        <Card className="shadow-lg p-6 rounded-lg">
          <div className="flex items-center justify-center text-5xl font-bold mb-4">
            17
          </div>
          <h3 className="text-lg font-semibold mb-2">Tech Guides</h3>
          <p className="text-gray-600 mb-4">
            Tutorials, videos, GitHub repos, and other resources for analyzing &
            visualizing blockchain data.
          </p>
          <Link
            className={buttonVariants({ variant: 'default' })}
            href="/guides"
          >
            Learn
          </Link>
        </Card>
      </div>
    </div>
  );
}
